# Generated by the genproj script
# Edit to your heart's content

PROG      := posh
CC        := gcc

SRCEXT    := c
OBJEXT    := o
DEPEXT    := d

SRCDIR    := src
DEPDIR    := dep
OBJDIR    := obj
BINDIR    := bin

CFLAGS    := -g -O0
LDFLAGS   :=


SRCFILES  := $(shell find . -name "*.$(SRCEXT)" -printf "%P\n")
OBJFILES  := $(SRCFILES:$(SRCDIR)/%.$(SRCEXT)=$(OBJDIR)/%.$(OBJEXT))
DEPFILES  := $(SRCFILES:$(SRCDIR)/%.$(SRCEXT)=$(DEPDIR)/%.$(DEPEXT))

$(OBJDIR)/%.$(OBJEXT): $(SRCDIR)/%.$(SRCEXT)
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -c $< -o $@

all: dirs $(BINDIR)/$(PROG)
	@echo "Done"

dirs: src dep obj bin
	@echo "Making directories"
	@mkdir -p $^

# -include $(DEPFILES)

$(DEPDIR)/%.$(DEPEXT): $(SRCDIR)/%.$(SRCEXT)
	@rm -f $@
	@$(CC) -MM $< > $@.$$
	@sed 's,\($*\)\.o[ :]*,$(OBJDIR)/\1.o $@ : ,g' <$@.$$ >$@
	@rm -f $@.$$

.PHONY: dirs

