# Automatically generated by the "genproj" script, by Joakker
# Edit to your heart's content
PROG      := posh
CC        := gcc

SRCDIR    := src
DEPDIR    := dep
OBJDIR    := obj
BINDIR    := bin

SRCEXT    := c
OBJEXT    := o
DEPEXT    := d

CFLAGS    := -g -O0
LDFLAGS   :=


GENFILES  :=
SRCFILES  := $(shell fd ".*\.c") $(addsuffix .o, $(basename $(GENFILES)))
OBJFILES  := $(SRCFILES:$(SRCDIR)/%.$(SRCEXT)=$(OBJDIR)/%.$(OBJEXT))
DEPFILES  := $(SRCFILES:$(SRCDIR)/%.$(SRCEXT)=$(DEPDIR)/%.$(DEPEXT))

DIRS      := $(SRCDIR) $(OBJDIR) $(BINDIR) $(DEPDIR)

$(OBJDIR)/%.$(OBJEXT): $(SRCDIR)/%.$(SRCEXT)
	@echo Compiling $<
	@$(CC) $(CFLAGS) -c $< -o $@

$(BINDIR)/$(PROG): $(DIRS) $(OBJFILES)
	@echo Linking $@
	@$(CC) $(CFLAGS) $(LDFLAGS) $^ -o $@

$(DIRS):
	@mkdir $@

-include $(DEPFILES)

clear: $(BINDIR)/$(PROG)
	@echo Cleaning targets
	@rm -f $(OBJFILES) $(DEPFILES) $<

$(DEPDIR)/%.$(DEPEXT): $(SRCDIR)/%.$(SRCEXT)
	@set -e; \
                    rm -f $@; \
                    $(CC) -MM $< > $@.$$$$; \
                    sed 's,\($*\)\.o[ :]*,$(OBJDIR)/\1.o $@ : ,g' < $@.$$$$ > $@; \
                    rm -f $@.$$$$

