# Automatically generated by the "genproj" script, by Joakker
# Edit to your heart's content
PROG      := posh
CC        := gcc

SRCDIR    := src
DEPDIR    := dep
OBJDIR    := obj
BINDIR    := bin

SRCEXT    := c
OBJEXT    := o
DEPEXT    := d

CFLAGS    := -g -O0
LDFLAGS   :=

SRCFILES  := $(shell fd ".*\.c")
OBJFILES  := $(SRCFILES:$(SRCDIR)/%.$(SRCEXT)=$(OBJDIR)/%.$(OBJEXT))
DEPFILES  := $(SRCFILES:$(SRCDIR)/%.$(SRCEXT)=$(DEPDIR)/%.$(DEPEXT))


$(OBJDIR)/%.$(OBJEXT): $(SRCDIR)/%.$(SRCEXT)
	@echo Compiling $<
	@$(CC) $(CFLAGS) -c $< -o $@

all: _dirs $(BINDIR)/$(PROG)
	@echo Done

$(BINDIR)/$(PROG): $(OBJFILES)
	@echo Linking $@
	@$(CC) $(CFLAGS) $(LDFLAGS) $^ -o $@

_dirs: 
	@mkdir $(SRCDIR) $(OBJDIR) $(BINDIR) $(DEPDIR)

-include $(DEPFILES)

clear: $(BINDIR)/$(PROG)
	@echo Cleaning targets
	@rm -f $(OBJFILES) $(DEPFILES) $<

$(DEPDIR)/%.$(DEPEXT): $(SRCDIR)/%.$(SRCEXT)
	@set -e; \
		rm -f $@; \
		$(CC) -MM $< > $@.$$$$; \
		sed 's,\($*\)\.o[ :]*,$(OBJDIR)/\1.o $@ : ,g' < $@.$$$$ > $@; \
		rm -f $@.$$$$

.PHONY: _dirs
